### ISSUE TITLE
Create all images specified in the formats parameter

### ISSUE THREAD

**Issue by wokalek** [matthiask/django-imagefield#14]
How can I specify that the ImageField field creates the necessary files specified in the formats parameter when saving a file in the admin panel?

I have field: 

```python
image = ImageField(
    'My Image Field', upload_to='photos', auto_add_fields=True, formats={
        f's{width}x{width}': ['default', ('crop', (width, width))]
        for width in [144, 204, 226, 274, 320, 370, 450]
    }
)
```

And when I save an image from the admin panel, I only have one format saved, this is the default thumbnail max 300x300 for viewing in the admin panel.

But the rest are not saved to the folder, for example: `django/media/__processed__/16f`

What should I do to create all the files specified in formats when saving?

**Comment by matthiask** [comment]
That's strange. It should just work, except if you override the formats in the `IMAGEFIELD_FORMATS` setting and/or if you set `IMAGEFIELD_AUTOGENERATE = False`. Not sure what's going on.

**Comment by wokalek** [comment]
@matthiask 

> That's strange. It should just work, except if you override the formats in the `IMAGEFIELD_FORMATS` setting and/or if you set `IMAGEFIELD_AUTOGENERATE = False`. Not sure what's going on.

No, I did not override `IMAGEFIELD_FORMATS`. 
I did not set `IMAGEFIELD_AUTOGENERATE = False`

Moreover, if I set `formats` on the field, the images stored in __processed__ are not deleted when the model element is deleted. Only the original.

**Comment by matthiask** [comment]
Ah, could it be that the `formats=` parameter is handled differently from `IMAGEFIELD_FORMATS`?

**Comment by wokalek** [comment]
> Ah, could it be that the formats= parameter is handled differently from IMAGEFIELD_FORMATS?

What do you mean?... Personally, I don't process formats in any way...

**Comment by matthiask** [comment]
Sorry, I have been thinking out loud. I'm looking into it right now.

**Comment by wokalek** [comment]
> > Ah, could it be that the formats= parameter is handled differently from IMAGEFIELD_FORMATS?
> 
> What do you mean?... Personally, I don't process formats in any way...

I tried to use the same dict for formats inside the IMAGEFIELD_FORMATS parameter:

```py
IMAGEFIELD_FORMATS={
    'photos.Photos.image': {
        f's{width}x{width}': ['default', ('crop', (width, width))]
        for width in [144, 204, 226, 274, 320, 370, 450]
    }
}
```

But it works exactly the same wrong

> Sorry, I have been thinking out loud. I'm looking into it right now.

Thanks a lot! (:

**Comment by matthiask** [comment]
Could you try again with an all lowercase field name, `photos.photo.image`? (Or `photos.photos.image` if the model class name really is `Photos`?)

**Comment by matthiask** [comment]
I have used your `formats={...}` in the imagefield test suite and have gotten the expected test failures because different images are produced.

**Comment by wokalek** [comment]
> Could you try again with an all lowercase field name, `photos.photo.image`? (Or `photos.photos.image` if the model class name really is `Photos`?)

I tried. I'm not sure if I specified it correctly in the example here, but I wrote everything correctly in the code.
Otherwise, the process_imagefields command would not create images for me according to the sizes specified in formats.


> I have used your formats={...} in the imagefield test suite and have gotten the expected test failures because different images are produced.

I see. But it's most likely just a typo in the specific example above.

In any case, I set formats specifically in the ImageField field of the model.

**Comment by matthiask** [comment]
Another thing, does `./manage.py process_imagefields --all` produce the images or does that also not work? 

Is there a way for you to share the project so that I can try it out myself?

**Comment by matthiask** [comment]
Ah sorry, you already wrote that `process_imagefields` works. Now I'm quite out of ideas.

**Comment by wokalek** [comment]
> Another thing, does ./manage.py process_imagefields --all produce the images or does that also not work?

The command `./manage.py process_imagefields --all ` works fine, all the images needed inside __processed__ are created.

The problem is that when creating/updating a model field (I work inside the admin panel), these images with the sizes specified in formats are not created in __processed__.

**Comment by matthiask** [comment]
Just to be safe, I have uploaded an image in a recent project to the feincms3-meta `meta_image` field which also uses `formats=` and it also works https://github.com/feincms/feincms3-meta/blob/53f033b25201bf64aa2e348c41f2291240530e10/feincms3_meta/models.py#L61-L69

So it *shouldn't* have broken recently. There's something else going on...

**Comment by wokalek** [comment]
I will try to prepare a basic example with the problem today.

**Comment by wokalek** [comment]
@matthiask I created [a repository](https://github.com/wokalek/django-imagefield-issue) with an example and I have as many as 2 incorrect behaviors in my opinion.

1. #### The first bug is in the *main* branch.

When I save an image, I get all the images specified in the formats parameter (as expected), and then I delete it, and all the images from __processed__ are deleted correctly, but the original image is not deleted.

Although in my project it is the original that is deleted, but not the only __processed__ image, which is created with the thumbnail preset, 300x300, by default (my images specified in formats were not created).

![main](https://github.com/user-attachments/assets/3e877b61-56d2-4055-9b8d-fe9a5632aa1c)

2. #### The second bug is in the *proxy* branch.

I use proxy models for the admin in my project and I thought that the problem could be in this... I was partially right.

```python
from content.models import Photo as PhotoModel

class Photo(PhotoModel):
    class Meta:
        proxy = True
```

When I create an image on this branch, the original file is created and 1 image by the default thumbnail preset, 300x300. My image sizes specified in formats are not created.

When I delete, neither the original nor the image in __processed__ is deleted.

![proxy](https://github.com/user-attachments/assets/b8ce8f9b-1772-4a6a-9a3b-0500d84a4d63)

I really hope that my example will help to solve the problems. If there are questions in installing dependencies or something else, I can help.

**Comment by matthiask** [comment]
Thanks! This is great. The `proxy` behavior doesn't surprise me since the `sender` doesn't match; I have to think a bit about how to approach this.

The 1. behavior is expected, since Django never deletes uploaded files if you do not explicitly opt-into it. django-imagefield only cleans up it's own files, and not those managed by Django. This behavior is described here:
https://docs.djangoproject.com/en/5.0/ref/models/fields/#django.db.models.fields.files.FieldFile.delete

> Note that when a model is deleted, related files are not deleted. If you need to cleanup orphaned files, you’ll need to handle it yourself (for instance, with a custom management command that can be run manually or scheduled to run periodically via e.g. cron).

**Comment by wokalek** [comment]
> The 1. behavior is expected, since Django never deletes uploaded files if you do not explicitly opt-into it. django-imagefield only cleans up it's own files, and not those managed by Django. This behavior is described here: https://docs.djangoproject.com/en/5.0/ref/models/fields/#django.db.models.fields.files.FieldFile.delete
> 
> > Note that when a model is deleted, related files are not deleted. If you need to cleanup orphaned files, you’ll need to handle it yourself (for instance, with a custom management command that can be run manually or scheduled to run periodically via e.g. cron).

Oh, I see... I actually knew about it, but somehow it slipped my mind. For some reason I thought that with a custom property the original files would be deleted too.

Thank you very much for the clarification.

Okay. Then the problem turns out to be specifically in my proxy model. I'll temporarily abandon the proxy and use the original. I hope you fix the proxy model issue.

**Comment by matthiask** [comment]
Yes, I'll definitely look into that. I like using proxy models too, so it's also my itch to scratch. Thanks for the repro!

**Comment by matthiask** [comment]
Hi @wokalek 

It would be great if you could test the current `main` version. I'm quite confident that it works as expected now.

**Comment by wokalek** [comment]
> Hi @wokalek
> 
> It would be great if you could test the current `main` version. I'm quite confident that it works as expected now.

I can test it when package update on pipy, right?
https://pypi.org/project/django-imagefield/#history

**Comment by wokalek** [comment]
@matthiask tested with pulling package from repo: 

```toml
django-imagefield = {git = "https://github.com/matthiask/django-imagefield"}
```

Works as expected!

![image](https://github.com/user-attachments/assets/1f38e1f7-3d80-4ef3-acea-46281c50d98f)

Thank you, can't wait for it to be updated in pypi too (:

**Comment by matthiask** [comment]
Nice! I have uploaded 0.19 to PyPI :)
