### ISSUE TITLE
How to get image path/content?

### ISSUE THREAD

**Issue by CleitonDeLima** [matthiask/django-imagefield#18]
I have a image field with format `small` configured, when use `instance.image.small` i received image small url. example:
`/media/__processed__/97f/image.jpeg`.

instead of the url, how do I retrieve the path? or even recover bytes from the image: `instance.logo.small.read()` ?

**Comment by matthiask** [comment]
If you call `instance.logo.process("small")` you get the part starting with `__processed__`; you can then use either Django's default file storage or, if files are stored and served locally, `MEDIA_ROOT` to find the file. That's the way I do it. Granted, it feels a bit ugly at times but it works well.

**Comment by CleitonDeLima** [comment]
> If you call `instance.logo.process("small")` you get the part starting with `__processed__`; you can then use either Django's default file storage or, if files are stored and served locally, `MEDIA_ROOT` to find the file. That's the way I do it. Granted, it feels a bit ugly at times but it works well.

Nice!
With media on S3, can I get the image data?

**Comment by matthiask** [comment]
Yes sure, something like the following (tested from memory without double checking):

```python
from django.core.files.storage import default_storage

path = instance.logo.process("small")
with default_storage.open(path, "rb") as f:
    data = f.read()
```

**Comment by CleitonDeLima** [comment]
> Yes sure, something like the following (untested, typed from memory without double checking):
> 
> ```python
> from django.core.files.storage import default_storage
> 
> path = instance.logo.process("small")
> with default_storage.open(path, "rb") as f:
>     data = f.read()
> ```

Thanks @matthiask!
